#!/usr/local/bin/python3
#####!/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/bin/python3.9
### #!/usr/local/Cellar/python\\@3.9/3.9.0_4/bin/python3
# python3, specifically the version from homebrew!
# given a stock symbol returns a (malformed) json
# you can correct the json using 
# json_pp -json_opt allow_singlequote,pretty 
#
# Example: filtering out one field.  jq is the answer.
# ./stock-stats  T | jq '."Oper. Margin"'
#
# TODO: add caching so we only hit internet at most once per day

import finviz,sys

if len(sys.argv) != 2 :
	print("USAGE: ", sys.argv[0], " <stockSymbol>")
	sys.exit(2)
SYM = sys.argv[1]

try:
	foo = finviz.get_stock(SYM)
except:
	print('ERROR: unknown stock symbol: ', SYM)
	sys.exit(3)

# canonical JSON uses double quotes; finviz returns single quotes
# needed to force return from finviz to a string for some reason
# TODO: how to test for type in python?  curious to know what finviz returns
import re
bar = re.sub(r"'",r'"',str(foo))

# print(foo)
print(bar)
