#!/usr/local/bin/python3
#####!/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/bin/python3.9
### #!/usr/local/Cellar/python\\@3.9/3.9.0_4/bin/python3
# python3, specifically the version from homebrew!
# given a stock symbol returns a (malformed) json
# you can correct the json using 
# json_pp -json_opt allow_singlequote,pretty 
#
# Example: filtering out one field.  jq is the answer.
# ./stock-stats  T | jq '."Oper. Margin"'
#
# 231020 - finviz stopped working; try yfinance
# https://github.com/ranaroussi/yfinance

import sys
import yfinance as yf

if len(sys.argv) != 2 :
	print("USAGE: ", sys.argv[0], " <stockSymbol>")
	exit(2)
SYM = sys.argv[1]

try:
	foo2 = yf.Ticker(SYM)
	foo = foo2.info	
except:
	print('ERROR: unknown stock symbol: ', SYM, file=sys.stderr)
	exit(3)

# canonical JSON uses double quotes; yfinance returns single quotes
# needed to force return from yfinance to a string for some reason
import re
bar = re.sub(r"'",r'"',str(foo))
# SOMETIMES someone uses an apostrophe as a contraction inside a string
baz = re.sub(r'([a-zA-Z])"s',r"\1's",bar)

print(baz)
